name: publish-nx-catalog-service.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14
          registry-url: 'https://registry.npmjs.org/'
          scope: 'telicent-oss'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - run: pnpm install
      - run: npx nx run @telicent-oss/rdfservice:build
      # - run: cd ./packages/RdfService && ls -la ./dist && npm publish --access public --provenance
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      #     NPM_CONFIG_PROVENANCE: true
      - run: npx nx run @telicent-oss/catalogservice:build

      - run: cd ./packages/RdfService && ls -la ./dist && npm publish --access public --provenance && cd -
      - run: cd ./packages/CatalogService && ls -la ./dist && npm publish --access public --provenance && cd -
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NPM_CONFIG_PROVENANCE: true