name: Publish NX
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
permissions:
  actions: read
  contents: read
  id-token: write # needed for provenance data generation

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          scope: 'telicent-oss'
          cache: "yarn"
          -token: ${{ secrets.NPM_REGISTRY }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        shell: bash

      - uses: nrwl/nx-set-shas@v4

      - name: publish packages
        run: npx nx release publish
        shell: bash
        env:
          NPM_CONFIG_PROVENANCE: true 