name: Publish NX
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: false
        default: ""
  release: [published]

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # need to fetch all the tags

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.1.0 # keep in sync with packageManager field in root package.json
          run_install: false
      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Ensure Nx is available
      - name: Install Nx CLI globally
        run: pnpm add -g nx
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          scope: 'telicent-oss'
          cache: 'pnpm' 

      - name: Apply updated version to packages and publish
      # switch from projects to --all when ready
        run: |
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          npx nx release version --specifier $VERSION
          npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
