name: Test release candidate
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.1.0 # keep in sync with packageManager field in root package.json
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Ensure Nx is available
      - name: Install Nx CLI globally
        run: pnpm add -g nx
      # switch from projects to --all when ready
      - uses: nrwl/nx-set-shas@v4
      - name: Build and publish packages
        run: |
          npx nx run-many --target=build --projects=@telicent-oss/rdfservice,@telicent-oss/ontologyservice
          npx nx run-many --target=publish --projects=@telicent-oss/rdfservice,@telicent-oss/ontologyservice
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
