name: Test release candidate
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.1.0 # keep in sync with packageManager field in root package.json
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: | 
          git checkout ${GITHUB_REF#refs/heads/}
          pnpm install
          pnpm dlx nx run-many -t test -p @telicent-oss/rdfservice @telicent-oss/ontologyservice 
